config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  namespace :admin do
    root 'application#index'

    resources :users, only: [:index, :show] do
      member do
        patch :archive
      end
    end
  end

  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :edit, :update]

  resources :skills, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      patch :recommend
    end
  end

  resources :projects, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get :edit_roles
      patch :update_roles
    end

    member do
      patch :upvote
    end

    resources :tags, only: [] do
      member do
        delete :remove
      end
    end

    resources :comments, only: [:new, :create]
  end

  resources :comments, only: [] do
    resources :answers, only: [:new, :create]
  end



  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: { registrations: 'api/v1/registrations' }

      resources :users, only: [:index, :show, :update]

      resources :users, only: [:create]

      resources :projects do
        member do
          get :edit_roles
          patch :update_roles
        end

        member do
          patch :upvote
        end

        resources :comments, only: [:create]
      end

      resources :skills, only: [:index, :create, :update, :destroy] do
        member do
          patch :recommend
        end
      end

      resources :comments, only: [] do
        resources :answers, only: [:new, :create]
      end


    end
  end

end

app/models/ability.rb
class Ability < ApplicationRecord
  has_many :skills
  has_many :users, through: :skills
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  after_create :author_watches_comment

  private

  def author_watches_comment
    if user.present? && !comment.watchers.include?(user)
      comment.watchers << user
      binding.pry
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
has_many :project, dependent: :destroy

validates :name, uniqueness: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :project
  has_many :answers, dependent: :destroy
  has_and_belongs_to_many :watchers, join_table: "comment_watchers", class_name: "User", uniq: true

  after_create :author_watches_me

  private

  def author_watches_me
    if user.present? && !self.watchers.include?(user)
      self.watchers << user
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :roles, dependent: :destroy
  has_many :users, through: :roles
  has_and_belongs_to_many :tags, uniq: true
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :images

  scope :filter_by_category, -> (category_id) { where category_id: category_id }

  attr_accessor :tag_names

  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  # settings do
  #   mappings dynamic: false do
  #     indexes :name, type: :text
  #     indexes :description, type: :text
  #     indexes :tags, type: :text
  #   end
  # end

  def tag_names=(names)
    @tag_names = names
    names.split.each do |name|
      self.tags << Tag.find_or_initialize_by(name: name)
    end
  end
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
  belongs_to :project

  def self.available_roles
      %w(manager editor viewer)
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  belongs_to :ability
  has_many :recommendations, dependent: :destroy

end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :project, dependent: :destroy
  has_many :roles, dependent: :destroy
  has_many :skills, dependent: :destroy
  has_many :abilities, through: :skills
  has_one_attached :photo

  scope :filter_by_skill, -> (skill_id) { where skill_id: skill_id }

  def active_for_authentication?
    super && archived_at.nil?
  end

  def inactive_message
    archived_at.nil? ? super : :archived
  end

  def to_s
    email
  end

  scope :excluding_archived, lambda { where(archived_at: nil) }

  def full_name
    "#{first_name} #{last_name}"
  end

  def archive
    self.update(archived_at: Time.now)
  end

  def role_on(project)
    roles.find_by(project_id: project).try(:name)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/shared/_answer-card.html.erb
<div class="answer-card">
  <%= image_tag(answer.user.photo) %>
  <div class="answer-info-wrap">
    <div class="answer-info">
      <h1><%= answer.user.full_name %></h1>
      <p>Il y a <%= time_ago_in_words(answer.created_at) %></p>
    </div>
    <div class="answer">
      <p><%= answer.answer %></p>
    </div>
  </div>
</div>

app/views/shared/_big-project-card.html.erb
<div class="big-project-card">
  <div class="big-project-card-info">
    <div class="big-project-card-main-info">
      <h1><%= project.name %></h1>
      <h4><%= project.category.category %></h4>
      <% if project.tags.any? %>
        <% project.tags.each do |tag| %>
          <%= render "tags/tag", tag: tag, project: project %>
        <% end %>
      <% end %>
    </div>
    <div class="big-project-card-images">
      <%= image_tag(project.images[0], :class => "img1") %>
      <%= image_tag(project.images[1], :class => "img2") %>
      <%= image_tag(project.images[2], :class => "img3") %>
      <%= image_tag(project.images[3], :class => "img4") %>
    </div>
    <div class="big-project-card-description">
      <p><%= project.description %></p>
    </div>
    <div class="big-project-card-user-link">
      <% if policy(project).update? %>
        <%= link_to 'Modifier mon projet', edit_project_path(project), class: 'button-select' %>
      <% end %>
      <% if policy(project).destroy? %>
        <%= link_to "Suprimer", project_path(project), method: :delete, data: { confirm: "Are you sure you want to delete this ticket?"}, class: 'button-select' %>
      <% end %>
    </div>
  </div>
  <div class="big-project-card-vote">
    <div class="big-project-card-vote-count">
      <p><%= project.votes.count %></p>
    </div>
    <%= link_to 'Voter', upvote_project_path(@project), method: :patch %>
  </div>
</div>

app/views/shared/_comment-card.html.erb
<div class="comment-card">
  <%= image_tag(comment.user.photo) %>
  <div class="comment-info-wrap">
    <div class="comment-info">
      <h2><%= comment.user.full_name %></h2>
      <p>Il y a <%= time_ago_in_words(comment.created_at) %></p>
    </div>
    <div class="comment">
      <p><%= comment.comment %></p>
    </div>

    <%= form_for [comment, answer] do |f| %>
      <div class="answer-form">
        <div class="field">
          <%= f.text_field :answer, placeholder: 'Ecrire une réponses', class: 'answer-input' %>
        </div>

        <div class="actions">
          <%= f.submit "Valider", id: 'button-valid'%>
        </div>
      </div>
    <% end %>

    <div class="answers-wrap">
      <% if comment.answers.any? %>
          <% comment.answers.each do |answer| %>
            <%= render 'shared/answer-card', answer: answer %>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_project-card.html.erb
<div id="project-card-wrap">
  <div class="project-card">
    <div class="project-info-image-wrap">
      <%= image_tag(project.images[0]) %>
      <div class="project-info">
        <div class="project-info">
          <h1> <%= project.name %> </h1>
          <h4><%= project.category.category %></h4>
        </div>
        <div class="project-description">
          <p><%= project.description %></p>
        </div>
      </div>


    </div>
    <div class="project-vote">
      <p><%= project.votes.count %></p>
    </div>
  </div>
</div>

app/views/shared/_skill-card.html.erb
<div class="skill-card-wrap">
  <div class="skill-card">
    <div class="skill">
      <div class="skill-info">
        <h2>  <%= skill.title %></h2>
        <p> <%= skill.description %> </p>
      </div>
      <div class="skill-rate">
        <p> <%= skill.rate %> </p>
      </div>
    </div>

    <div class="skill-recommendation">
      <% if skill.recommendations.any? %>
        <p><%= skill.recommendations[0].user.full_name %> et <%= skill.recommendations.count - 1 %> autres utilisateurs ont recommendé cette compétences</p>
      <% end %>
      <%= link_to 'Recommander', recommend_skill_path(skill), method: :patch, class: 'button-select' %>
    </div>

  </div>
</div>

app/views/shared/_small-user-card.html.erb
<div class="small-user-card-wrap">
  <div class="small-user-card">
    <%= image_tag(user.photo) if user.photo.attached? %>
    <div class="small-user-card-info">
      <h1> <%= user.full_name %> </h1>
      <h2> <%= user.title %> </h2>
    </div>
  </div>
</div>

app/views/shared/_user-card.html.erb
<div class="user-card-wrap">
    <% if @user == current_user %>
      <%= link_to edit_user_path, class: 'edit-link' do %>
        <i class="fas fa-edit"></i>
      <% end %>
    <% end %>
  <div class="user-card">
    <%= image_tag(user.photo) if user.photo.attached? %>
    <div class="user-info-wrap">
      <div class="user-info">
        <h1> <%= user.full_name %> </h1>
        <h3> <%= user.title %> </h3>
        <div class="user-skill">
          <% if user.skills.any? %>
            <% user.skills.each do |skill| %>
              <h4><%= skill.title %></h4>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="user-description">
        <p> <%= user.description %> </p>
      </div>
    </div>
  </div>
</div>