config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  namespace :admin do
    root 'application#index'

    resources :users, only: [:index, :show] do
      member do
        patch :archive
      end
    end
  end

  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :edit, :update]

  resources :skills, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      patch :recommend
    end
  end

  resources :projects, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get :edit_roles
      patch :update_roles
    end

    member do
      patch :upvote
    end

    resources :tags, only: [] do
      member do
        delete :remove
      end
    end

    resources :comments, only: [:new, :create]
  end

  resources :comments, only: [] do
    resources :answers, only: [:new, :create]
  end



  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: { registrations: 'api/v1/registrations' }

      resources :users, only: [:index, :show, :update]

      resources :users, only: [:create]

      resources :projects do
        member do
          get :edit_roles
          patch :update_roles
        end

        member do
          patch :upvote
        end

        resources :comments, only: [:create]
      end

      resources :skills, only: [:index, :create, :update, :destroy] do
        member do
          patch :recommend
        end
      end

      resources :comments, only: [] do
        resources :answers, only: [:new, :create]
      end


    end
  end

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :roles, dependent: :destroy
  has_many :users, through: :roles
  has_and_belongs_to_many :tags, uniq: true
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :images

  scope :filter_by_category, -> (category_id) { where category_id: category_id }

  attr_accessor :tag_names

  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  # settings do
  #   mappings dynamic: false do
  #     indexes :name, type: :text
  #     indexes :description, type: :text
  #     indexes :tags, type: :text
  #   end
  # end

  def tag_names=(names)
    @tag_names = names
    names.split.each do |name|
      self.tags << Tag.find_or_initialize_by(name: name)
    end
  end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::V1::ApplicationController


  before_action :set_user, only: [:new, :create, :edit, :update, :edit_roles, :destroy, :upvote]
  before_action :set_project, only: [:show, :edit, :update, :edit_roles, :update_roles, :destroy, :upvote]


  def index
    @projects = policy_scope(Project)
    render json: @projects
  end

  def show
    authorize @project, :show?
    render json: @project
  end

  def create
    @project = @user.project.build(project_params)
    binding.pry
    authorize @project, :create?
    if @project.save
      Role.create(role: 'manager', user: @user, project: @project)
      render json: @project
    else
      render json: { error: "Votre projet n'a pas été crée" }, status: 422
    end
  end

  def update
    authorize @project, :update?
    if @project.update(project_params)
      render json: @project
    else
      render json: { error: "Votre projet n'a pas été modifié" }, status: 422
    end
  end

  def destroy
    authorize @project, :destroy?
    if @project.destroy
      head :no_content
    else
      render json: { error: "Votre projet n'a pas été suprimé" }, status: 422
    end
  end

  def update_roles
    authorize @project, :update_roles?
    role_data = params.fetch(:roles, [])
    role_data.each do |user_id, role_name|
      binding.pry
      if role_name.present?
        Role.find_by(user_id: user_id).delete
        @role = Role.new(user_id: user_id, project: @project, role: role_name)
        @role.save!
      end
    end
    head(:created)
  end

  def upvote
    authorize @project, :upvote?
    @vote = @project.votes.build(user: @user)
    unless Vote.find_by(user: @user, project: @project).nil?
      render json: { error: "Vous avez deja voté" }, status: 422
    else
      @vote.save!
      head(:created)
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def project_params
    params.require(:project).permit(:name, :description, :website_url, :linkedin_url, :twitter_url, :facebook_url, :instagram_url, :category_id, :tag_names)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_user, only: [:new, :create, :edit, :update, :edit_roles, :destroy, :upvote]
  before_action :set_project, only: [:show, :edit, :update, :edit_roles, :update_roles, :destroy, :upvote]
  skip_after_action :verify_authorized, :verify_policy_scoped, only: [:search, :index]
  before_action :authenticate_user!, only: [:upvote]

  def index
    @projects = policy_scope(Project)
    @projects = Project.filter_by_category(params[:c]) if params[:c].present?

    @categories = Category.all

  end

  def show
    authorize @project, :show?
    @comment = Comment.new
    @answer = Answer.new
  end

  def new
    @project = @user.project.build
    authorize @project, :new?
    @categories = Category.all
  end

  def create
    @project = @user.project.build(project_params)
    authorize @project, :create?
    if @project.save
      Role.create(role: 'manager', user: @user, project: @project)
      flash[:notice] = "Votre projet a bien été crée !"
      redirect_to project_path(@project)
    else
      flash[:alert] = "Votre projet n'a pas été crée"
      render :new
    end
  end

  def edit
    authorize @project, :update?
    @categories = Category.all
  end

  def update
    authorize @project, :update?
    if @project.update(project_params)
      flash[:notice] = "Votre projet a bien été modifié !"
      redirect_to project_path(@project)
    else
      flash[:alert] = "Votre projet n'a pas été modifié !"
      render :edit
    end
  end

  def destroy
    authorize @project, :destroy?
    @project.destroy
    flash[:notice] = "Votre projet a bien été supprimé !"
    redirect_to user_path(@user)
  end

  def edit_roles
    authorize @project, :update_roles?
    @users = @project.users
  end

  def update_roles
    authorize @project, :update_roles?
    role_data = params.fetch(:roles, [])
    role_data.each do |user_id, role_name|
      if role_name.present?
        Role.find_by(user_id: user_id).delete
        @role = Role.new(user_id: user_id, project: @project, role: role_name)
        @role.save!
      end
    end
    flash[:notice] = "Les roles ont bien été modifié"
    redirect_to project_path(@project)
  end

  def search
    if params[:q].present?
      @projects = Project.search(params[:q]).records
      render "projects/index"
    end
  end

  def upvote
    authorize @project, :upvote?
    @vote = @project.votes.build(user: @user)
    unless Vote.find_by(user: @user, project: @project).nil?
      flash[:alert] = "Vous avez déja voté !"
    else
      @vote.save!
    end
    redirect_to project_path(@project)
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def project_params
    params.require(:project).permit(:name, :description, :website_url, :linkedin_url, :twitter_url, :facebook_url, :instagram_url, :category_id, :tag_names, images: [])
  end
end

app/helpers/api/v1/projects_helper.rb
module Api::V1::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="form-wrapper">
  <div class="form">

    <h2>Créer un projet</h2>

    <%= form_for @project do |f| %>

      <div class="field">

        <%= f.text_field :name, placeholder: 'Nom du projet', class: 'form-field' %>
      </div>

      <div class="field">

        <%= f.text_area :description, placeholder: 'Description du projet', class: 'form-field' %>
      </div>

      <div class="field">

        <%= f.text_field :website_url, placeholder: 'URL du site internet', class: 'form-field' %>
      </div>

      <div class="field">

        <%= f.text_field :linkedin_url, placeholder: 'URL Linkedin', class: 'form-field' %>
      </div>

      <div class="field">

        <%= f.text_field :twitter_url, placeholder: 'URL Twitter', class: 'form-field' %>
      </div>

      <div class="field">

        <%= f.text_field :facebook_url, placeholder: 'URL Facebook', class: 'form-field' %>
      </div>

      <div class="field">

        <%= f.text_field :instagram_url, placeholder: 'URL Instagram', class: 'form-field' %>
      </div>

      <div class="field">

        <%= f.text_field :tag_names, placeholder: 'Tags', class: 'form-field' %>
      </div>

      <div class="field">
        <%= f.label :images %>
        <%= f.file_field :images, :multiple => true %>
      </div>

      <div class="field">
        <%= f.label :category_id %>
        <%= f.select :category_id, @categories.map { |s| [s.category, s.id] } %>
      </div>

      <div class="actions">
        <%= f.submit "Valider", id: 'button-valid'%>
      </div>
    <% end %>

  </div>
</div>

app/views/projects/edit.html.erb
<%= render "form", user: @user, project: @project %>

app/views/projects/edit_roles.html.erb
<%= form_for @project, :url => {:controller => "projects", :action => "update_roles"} do |f| %>

<table class="roles">
  <% @project.users.each do |user| %>
    <tr>
      <th>
        <%= label_tag dom_id(user), user.full_name %>
      </th>
      <td>
        <%= select_tag dom_id(user), options_for_select(roles, user.role_on(@project)), name: "roles[#{user.id}]", include_blank: true %>
      </td>
    </tr>
  <% end %>
</table>

  <div class="actions">
    <%= f.submit "Valider"%>
  </div>
<% end %>

app/views/projects/index.html.erb
<div id="projects-index-page-wrap">

  <div id="search-area-wrap">

    <h2>Rechercher:</h2>

      <%= form_tag projects_path, role: 'search', method: :get, class: 'search-area' do |f| %>

        <div class="search-field">
          <i class="fas fa-search"></i>
          <%= text_field_tag :q, params[:q], class: "input-field" %>
        </div>


        <%= select_tag(:c, options_from_collection_for_select(@categories, :id, :category), {:style => "padding: 0.5rem; border-radius: 8px; "} )%>

        <button id="button-valid">Valider</button>

      <% end %>


  </div>



  <div id="projects-index-wrap">

    <div id="projects-index">
      <% @projects.each do |project| %>
        <%= link_to project_path(project) do %>
          <%= render 'shared/project-card', project: project %>
        <% end %>
      <% end %>
    </div>
  </div>


</div>

app/views/projects/new.html.erb
<%= form_for [@user, @project] do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :website_url %><br>
    <%= f.text_field :website_url %>
  </div>

  <div class="field">
    <%= f.label :linkedin_url %><br>
    <%= f.text_field :linkedin_url %>
  </div>

  <div class="field">
    <%= f.label :twitter_url %><br>
    <%= f.text_field :twitter_url %>
  </div>

  <div class="field">
    <%= f.label :facebook_url %><br>
    <%= f.text_field :facebook_url %>
  </div>

  <div class="field">
    <%= f.label :instagram_url %><br>
    <%= f.text_field :instagram_url %>
  </div>

  <%= f.label :category_id %>
  <%= f.select :category_id, @categories.map { |s| [s.category, s.id] } %>

  <div class="actions">
    <%= f.submit "Créer"%>
  </div>
<% end %>

app/views/projects/show.html.erb
<div class="project-show-page-wrap">
  <div class="big-project-card-wrap">
    <%= render 'shared/big-project-card', project: @project %>
  </div>

  <div class="project-show-contributor-wrap">
    <div class="project-show-list-top">
      <h2>Contributeur:</h2>
      <% if policy(@project).update_roles? %>
        <%= link_to 'Modifier', edit_roles_project_path(@project), class: 'button-select' %>
      <% end %>
    </div>

    <% @project.users.each do |user| %>
          <%= render 'shared/small-user-card', user: user %>
    <% end %>
  </div>


  <div class="project-show-comment-wrap">
    <h2>Commentaires:</h2>

    <div class="project-show-comment">

      <%= form_for [@project, @comment] do |f| %>
        <div class="comment-form">
          <div class="field">
            <%= f.text_field :comment, placeholder: 'Ecrire un commentaire', class: 'comment-input' %>
          </div>

          <div class="actions">
            <%= f.submit "Valider", id: 'button-valid'%>
          </div>
        </div>
      <% end %>


      <% if @project.comments.any? %>
          <% @project.comments.each do |comment| %>
              <%= render 'shared/comment-card', comment: comment, answer: @answer %>
          <% end %>
      <% end %>
    </div>


  </div>


</div>